apiVersion: v1
kind: Service
metadata:
  name: {{ include "booksvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "booksvc.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc-web-port
  selector:
    {{- include "booksvc.matchLabels" . | nindent 4 }}
