---
kind: pipeline
name: authsvc

workspace:
  base: /go
  path: src/github.com/Buzzvil/stella

steps:
- name: test authsvc
  image: golang:1.11
  commands:
  - cd authsvc
  - go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - migrate -source file://db/migrations -database $DATABASE_URL up
  - go test -v ./...
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable

services:
- name: postgres
  image: postgres
  ports:
  - 5432
---
kind: pipeline
name: frontend

steps:
- name: test frontend
  image: node:10.15
  commands:
  - cd frontend
  - npm install
  - npm test
