---
kind: pipeline
name: authsvc

workspace:
  base: /go
  path: src/github.com/Buzzvil/stella

steps:
- name: Test
  image: golang:1.11
  commands:
  - cd authsvc
  - go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - migrate -source file://db/migrations -database $DATABASE_URL up
  - go test -v ./...
  - echo -n $DRONE_BRANCH-$(echo $DRONE_COMMIT_SHA | head -c7) > .tags
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable

- name: Publish
  image: plugins/gcr
  settings:
    repo: gcr.io/devops-229509/stella/authsvc
    context: authsvc
    dockerfile: authsvc/Dockerfile
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
      - publish

services:
- name: postgres
  image: postgres
  ports:
  - 5432

---
kind: pipeline
name: booksvc

workspace:
  base: /go
  path: src/github.com/Buzzvil/stella

steps:
- name: Test
  image: golang:1.11
  commands:
  - cd booksvc
  - go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - migrate -source file://db/migrations -database $DATABASE_URL up
  - go test -v ./...
  - echo -n $DRONE_BRANCH-$(echo $DRONE_COMMIT_SHA | head -c7) > .tags
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable

- name: Publish
  image: plugins/gcr
  settings:
    repo: gcr.io/devops-229509/stella/booksvc
    context: booksvc
    dockerfile: booksvc/Dockerfile
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
      - publish

services:
- name: postgres
  image: postgres
  ports:
  - 5432

---
kind: pipeline
name: frontend

steps:
- name: test frontend
  image: node:10.15
  commands:
  - cd frontend
  - npm install
  - npm test
  - echo -n $DRONE_BRANCH-$(echo $DRONE_COMMIT_SHA | head -c7) > .tags

- name: Publish
  image: plugins/gcr
  settings:
    repo: gcr.io/devops-229509/stella/frontend
    context: frontend
    dockerfile: frontend/Dockerfile
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
      - publish

---
kind: pipeline
name: ratingsvc

workspace:
  base: /go
  path: src/github.com/Buzzvil/stella

steps:
- name: test ratingsvc
  image: golang:1.11
  commands:
  - cd ratingsvc
  - go test -v ./...
  - echo -n $DRONE_BRANCH-$(echo $DRONE_COMMIT_SHA | head -c7) > .tags

- name: Publish
  image: plugins/gcr
  settings:
    repo: gcr.io/devops-229509/stella/ratingsvc
    context: ratingsvc
    dockerfile: ratingsvc/Dockerfile
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
      - publish

---
kind: pipeline
name: rentalsvc

workspace:
  base: /go
  path: src/github.com/Buzzvil/stella

steps:
- name: Test
  image: golang:1.11
  commands:
  - cd rentalsvc
  - go test -v ./...
  - echo -n $DRONE_BRANCH-$(echo $DRONE_COMMIT_SHA | head -c7) > .tags

- name: Publish
  image: plugins/gcr
  settings:
    repo: gcr.io/devops-229509/stella/rentalsvc
    context: rentalsvc
    dockerfile: rentalsvc/Dockerfile
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
      - publish
