kind: pipeline
name: build

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
    - echo $DRONE_REPO_PRIVATE
    - cat /root/.netrc
    - git clone $DRONE_GIT_HTTP_URL

- name: test authsvc
  image: golang:1.11
  commands:
  - cd authsvc
  - go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - migrate -source file://db/migrations -database $DATABASE_URL up
  - make integration-test
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable

services:
- name: postgres
  image: postgres
  ports:
  - 5432
