// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ratingsvc.proto

package stella_rating_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rating struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{0}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Rating) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Rating) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Rating) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type GetRatingRequest struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingRequest) Reset()         { *m = GetRatingRequest{} }
func (m *GetRatingRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatingRequest) ProtoMessage()    {}
func (*GetRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{1}
}

func (m *GetRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingRequest.Unmarshal(m, b)
}
func (m *GetRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingRequest.Marshal(b, m, deterministic)
}
func (m *GetRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingRequest.Merge(m, src)
}
func (m *GetRatingRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatingRequest.Size(m)
}
func (m *GetRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingRequest proto.InternalMessageInfo

func (m *GetRatingRequest) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type GetRatingResponse struct {
	Score                float32  `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingResponse) Reset()         { *m = GetRatingResponse{} }
func (m *GetRatingResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatingResponse) ProtoMessage()    {}
func (*GetRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{2}
}

func (m *GetRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingResponse.Unmarshal(m, b)
}
func (m *GetRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingResponse.Marshal(b, m, deterministic)
}
func (m *GetRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingResponse.Merge(m, src)
}
func (m *GetRatingResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatingResponse.Size(m)
}
func (m *GetRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingResponse proto.InternalMessageInfo

func (m *GetRatingResponse) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *GetRatingResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUserRatingRequest struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRatingRequest) Reset()         { *m = GetUserRatingRequest{} }
func (m *GetUserRatingRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRatingRequest) ProtoMessage()    {}
func (*GetUserRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{3}
}

func (m *GetUserRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRatingRequest.Unmarshal(m, b)
}
func (m *GetUserRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRatingRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRatingRequest.Merge(m, src)
}
func (m *GetUserRatingRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRatingRequest.Size(m)
}
func (m *GetUserRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRatingRequest proto.InternalMessageInfo

func (m *GetUserRatingRequest) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *GetUserRatingRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListRatingsResponse struct {
	Ratings              []*Rating `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRatingsResponse) Reset()         { *m = ListRatingsResponse{} }
func (m *ListRatingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRatingsResponse) ProtoMessage()    {}
func (*ListRatingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{4}
}

func (m *ListRatingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatingsResponse.Unmarshal(m, b)
}
func (m *ListRatingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatingsResponse.Marshal(b, m, deterministic)
}
func (m *ListRatingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatingsResponse.Merge(m, src)
}
func (m *ListRatingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRatingsResponse.Size(m)
}
func (m *ListRatingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatingsResponse proto.InternalMessageInfo

func (m *ListRatingsResponse) GetRatings() []*Rating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

type UpsertRatingRequest struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score                float32  `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRatingRequest) Reset()         { *m = UpsertRatingRequest{} }
func (m *UpsertRatingRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRatingRequest) ProtoMessage()    {}
func (*UpsertRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{5}
}

func (m *UpsertRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRatingRequest.Unmarshal(m, b)
}
func (m *UpsertRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRatingRequest.Marshal(b, m, deterministic)
}
func (m *UpsertRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRatingRequest.Merge(m, src)
}
func (m *UpsertRatingRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRatingRequest.Size(m)
}
func (m *UpsertRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRatingRequest proto.InternalMessageInfo

func (m *UpsertRatingRequest) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *UpsertRatingRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpsertRatingRequest) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *UpsertRatingRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type DeleteRequest struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61e79acbe641d6ef, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *DeleteRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Rating)(nil), "stella.rating.v1.Rating")
	proto.RegisterType((*GetRatingRequest)(nil), "stella.rating.v1.GetRatingRequest")
	proto.RegisterType((*GetRatingResponse)(nil), "stella.rating.v1.GetRatingResponse")
	proto.RegisterType((*GetUserRatingRequest)(nil), "stella.rating.v1.GetUserRatingRequest")
	proto.RegisterType((*ListRatingsResponse)(nil), "stella.rating.v1.ListRatingsResponse")
	proto.RegisterType((*UpsertRatingRequest)(nil), "stella.rating.v1.UpsertRatingRequest")
	proto.RegisterType((*DeleteRequest)(nil), "stella.rating.v1.DeleteRequest")
}

func init() { proto.RegisterFile("ratingsvc.proto", fileDescriptor_61e79acbe641d6ef) }

var fileDescriptor_61e79acbe641d6ef = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0xae, 0x9a, 0x40,
	0x14, 0x05, 0x7d, 0x68, 0xbd, 0xef, 0x99, 0xf7, 0x3a, 0xcf, 0xb4, 0x04, 0x17, 0x25, 0xd3, 0xb4,
	0x61, 0x35, 0xa6, 0xf6, 0x03, 0xba, 0xa9, 0x31, 0x24, 0x6e, 0x8a, 0xb1, 0x8b, 0x6e, 0x1a, 0xc5,
	0x5b, 0x43, 0x82, 0x0c, 0x65, 0x06, 0x13, 0xd3, 0x3f, 0xe9, 0xd7, 0x36, 0x30, 0xa8, 0x28, 0x68,
	0x48, 0xfa, 0x96, 0xf7, 0x72, 0x2e, 0xe7, 0xcc, 0x3d, 0x27, 0x17, 0x1e, 0x93, 0xa5, 0x0c, 0xa2,
	0x8d, 0xd8, 0xf9, 0x2c, 0x4e, 0xb8, 0xe4, 0xe4, 0x49, 0x48, 0x0c, 0xc3, 0x25, 0x53, 0x7d, 0xb6,
	0xfb, 0x64, 0x0d, 0x37, 0x9c, 0x6f, 0x42, 0x1c, 0xe5, 0xdf, 0x57, 0xe9, 0xaf, 0x11, 0x6e, 0x63,
	0xb9, 0x57, 0x70, 0x1a, 0x41, 0xc7, 0xcb, 0x91, 0x64, 0x08, 0x3d, 0x8c, 0x64, 0x20, 0xf7, 0x3f,
	0x83, 0xb5, 0xa9, 0xdb, 0xba, 0x63, 0x78, 0xaf, 0x54, 0xc3, 0x5d, 0x93, 0x01, 0x18, 0xc2, 0xe7,
	0x09, 0x9a, 0x2d, 0x5b, 0x77, 0x5a, 0x9e, 0x2a, 0xc8, 0x5b, 0xe8, 0xa6, 0x02, 0x93, 0x6c, 0xa0,
	0x9d, 0x0f, 0x74, 0xb2, 0xd2, 0x5d, 0x13, 0x13, 0xba, 0x3e, 0xdf, 0x6e, 0x31, 0x92, 0xe6, 0x9d,
	0xad, 0x3b, 0x3d, 0xef, 0x50, 0xd2, 0x11, 0x3c, 0x4d, 0x51, 0x2a, 0x4a, 0x0f, 0x7f, 0xa7, 0x28,
	0xe4, 0x4d, 0x66, 0xfa, 0x05, 0x5e, 0x97, 0x06, 0x44, 0xcc, 0x23, 0x81, 0x27, 0x39, 0x7a, 0x59,
	0xce, 0x00, 0x0c, 0x9f, 0xa7, 0x91, 0xcc, 0x45, 0x1a, 0x9e, 0x2a, 0xe8, 0x0c, 0x06, 0x53, 0x94,
	0x0b, 0x81, 0x49, 0x73, 0xd6, 0xf2, 0xcb, 0x5a, 0xe5, 0x97, 0x51, 0x17, 0x9e, 0x67, 0x81, 0x28,
	0xf4, 0x88, 0xa3, 0xa0, 0x31, 0x74, 0x0b, 0x23, 0x4c, 0xdd, 0x6e, 0x3b, 0xf7, 0x63, 0x93, 0x5d,
	0xfa, 0xc0, 0x0a, 0xfa, 0x03, 0x90, 0xfe, 0x81, 0xe7, 0x45, 0x2c, 0x30, 0x91, 0x2f, 0xa0, 0xeb,
	0xb4, 0x91, 0x76, 0x79, 0x23, 0xd7, 0x7d, 0x98, 0x40, 0xff, 0x2b, 0x86, 0x28, 0xf1, 0xbf, 0x68,
	0xc7, 0x7f, 0xef, 0xa0, 0xaf, 0xe4, 0xcf, 0x31, 0xd9, 0x05, 0x3e, 0x92, 0xef, 0xd0, 0x3b, 0xfa,
	0x45, 0x68, 0x75, 0x0b, 0x97, 0xee, 0x5b, 0xef, 0x6f, 0x62, 0xd4, 0x7e, 0xa9, 0x46, 0xe6, 0xd0,
	0x3f, 0xb3, 0x91, 0x7c, 0xac, 0x9d, 0xab, 0xf8, 0x6c, 0x5d, 0x75, 0x82, 0x6a, 0xe4, 0x07, 0xdc,
	0x97, 0xdc, 0x6c, 0x24, 0xf7, 0x43, 0x15, 0x53, 0x13, 0x08, 0xaa, 0x91, 0x15, 0x3c, 0x66, 0x1f,
	0x4e, 0x82, 0x44, 0x63, 0xc9, 0x8d, 0x39, 0xbe, 0xc1, 0x43, 0x39, 0x42, 0xa4, 0x66, 0xb0, 0x26,
	0x62, 0x37, 0x57, 0xe2, 0xc2, 0x43, 0x11, 0x0c, 0xf5, 0xcb, 0x77, 0x55, 0xec, 0x59, 0x70, 0xac,
	0x37, 0x4c, 0xdd, 0x17, 0x76, 0xb8, 0x2f, 0x6c, 0x92, 0xdd, 0x17, 0xaa, 0xad, 0x3a, 0x79, 0xe7,
	0xf3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x4c, 0x86, 0xb8, 0xa4, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RatingServiceClient is the client API for RatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RatingServiceClient interface {
	GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*GetRatingResponse, error)
	GetUserRating(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*Rating, error)
	ListRatings(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error)
	ListUserRatings(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error)
	UpsertRating(ctx context.Context, in *UpsertRatingRequest, opts ...grpc.CallOption) (*Rating, error)
	DeleteRating(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type ratingServiceClient struct {
	cc *grpc.ClientConn
}

func NewRatingServiceClient(cc *grpc.ClientConn) RatingServiceClient {
	return &ratingServiceClient{cc}
}

func (c *ratingServiceClient) GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*GetRatingResponse, error) {
	out := new(GetRatingResponse)
	err := c.cc.Invoke(ctx, "/stella.rating.v1.RatingService/GetRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetUserRating(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*Rating, error) {
	out := new(Rating)
	err := c.cc.Invoke(ctx, "/stella.rating.v1.RatingService/GetUserRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) ListRatings(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error) {
	out := new(ListRatingsResponse)
	err := c.cc.Invoke(ctx, "/stella.rating.v1.RatingService/ListRatings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) ListUserRatings(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error) {
	out := new(ListRatingsResponse)
	err := c.cc.Invoke(ctx, "/stella.rating.v1.RatingService/ListUserRatings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) UpsertRating(ctx context.Context, in *UpsertRatingRequest, opts ...grpc.CallOption) (*Rating, error) {
	out := new(Rating)
	err := c.cc.Invoke(ctx, "/stella.rating.v1.RatingService/UpsertRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) DeleteRating(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/stella.rating.v1.RatingService/DeleteRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServiceServer is the server API for RatingService service.
type RatingServiceServer interface {
	GetRating(context.Context, *GetRatingRequest) (*GetRatingResponse, error)
	GetUserRating(context.Context, *GetUserRatingRequest) (*Rating, error)
	ListRatings(context.Context, *GetRatingRequest) (*ListRatingsResponse, error)
	ListUserRatings(context.Context, *GetUserRatingRequest) (*ListRatingsResponse, error)
	UpsertRating(context.Context, *UpsertRatingRequest) (*Rating, error)
	DeleteRating(context.Context, *DeleteRequest) (*empty.Empty, error)
}

// UnimplementedRatingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRatingServiceServer struct {
}

func (*UnimplementedRatingServiceServer) GetRating(ctx context.Context, req *GetRatingRequest) (*GetRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRating not implemented")
}
func (*UnimplementedRatingServiceServer) GetUserRating(ctx context.Context, req *GetUserRatingRequest) (*Rating, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRating not implemented")
}
func (*UnimplementedRatingServiceServer) ListRatings(ctx context.Context, req *GetRatingRequest) (*ListRatingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRatings not implemented")
}
func (*UnimplementedRatingServiceServer) ListUserRatings(ctx context.Context, req *GetUserRatingRequest) (*ListRatingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserRatings not implemented")
}
func (*UnimplementedRatingServiceServer) UpsertRating(ctx context.Context, req *UpsertRatingRequest) (*Rating, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRating not implemented")
}
func (*UnimplementedRatingServiceServer) DeleteRating(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRating not implemented")
}

func RegisterRatingServiceServer(s *grpc.Server, srv RatingServiceServer) {
	s.RegisterService(&_RatingService_serviceDesc, srv)
}

func _RatingService_GetRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.rating.v1.RatingService/GetRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRating(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetUserRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetUserRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.rating.v1.RatingService/GetUserRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetUserRating(ctx, req.(*GetUserRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_ListRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).ListRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.rating.v1.RatingService/ListRatings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).ListRatings(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_ListUserRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).ListUserRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.rating.v1.RatingService/ListUserRatings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).ListUserRatings(ctx, req.(*GetUserRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_UpsertRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).UpsertRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.rating.v1.RatingService/UpsertRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).UpsertRating(ctx, req.(*UpsertRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_DeleteRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).DeleteRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.rating.v1.RatingService/DeleteRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).DeleteRating(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RatingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stella.rating.v1.RatingService",
	HandlerType: (*RatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRating",
			Handler:    _RatingService_GetRating_Handler,
		},
		{
			MethodName: "GetUserRating",
			Handler:    _RatingService_GetUserRating_Handler,
		},
		{
			MethodName: "ListRatings",
			Handler:    _RatingService_ListRatings_Handler,
		},
		{
			MethodName: "ListUserRatings",
			Handler:    _RatingService_ListUserRatings_Handler,
		},
		{
			MethodName: "UpsertRating",
			Handler:    _RatingService_UpsertRating_Handler,
		},
		{
			MethodName: "DeleteRating",
			Handler:    _RatingService_DeleteRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ratingsvc.proto",
}
