authsvc:
  env:
    DATABASE_URL: postgres://postgres:Tvdn46sPaawLM(w@stella-db-postgresql:5432/authsvc?sslmode=disable
    SLACK_OAUTH_CLIENT_ID: '2921750999.570187289585'
    SLACK_OAUTH_CLIENT_SECRET: 'c5d10427a5b04db27628f71a57b5686a'
    WEB_HOST: 'https://library.buzzvil.com'
global:
  hosts:
  - library.buzzvil.com
  gateway:
    name: stella
    tls:
      enabled: true
      secretName: stella-certs
