authsvc:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 64Mi

  env: {}

booksvc:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 64Mi

frontend:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 64Mi

global:
  webHost: library.buzzvil.com
  hosts:
  - library.buzzvil.com
  gateway:
    name: stella
    tls:
      enabled: true
      secretName: stella-certs
