apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "stella.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stella.labels" . | nindent 4 }}
spec:
  workloadLabels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  filters:
  - listenerMatch:
      listenerProtocol: HTTP
      listenerType: SIDECAR_INBOUND
    filterName: envoy.grpc_web
    filterType: HTTP
    filterConfig: {}
    insertPosition:
      index: FIRST
