apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "stella.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stella.labels" . | nindent 4 }}
spec:
  selector:
    app: public-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- if .Values.global.hosts }}
      {{- range .Values.global.hosts }}
      - {{ . | quote }}
      {{- end }}
    {{- else }}
      - "*"
    {{- end }}
    {{- if .Values.global.gateway.tls.enabled }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- if .Values.global.gateway.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    {{- if .Values.global.hosts }}
      {{- range .Values.global.hosts }}
        - {{ . | quote }}
      {{- end }}
    {{- else }}
      - "*"
    {{- end }}
    tls:
      credentialName: {{ .Values.global.gateway.tls.secretName }}
      mode: SIMPLE
  {{- end }}
