apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authsvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authsvc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authsvc.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authsvc.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/go/bin/authsvc"]
          ports:
            - name: grpc
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
