apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "authsvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authsvc.labels" . | nindent 4 }}
spec:
  hosts:
  - '*'
  gateways:
  - {{ .Values.global.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /envoy.service.auth
    route:
    - destination:
        host: {{ include "authsvc.fullname" . }}
        port:
          number: {{ .Values.service.grpc.port }}
