apiVersion: v1
kind: Service
metadata:
  name: {{ include "authsvc.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authsvc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "authsvc.matchLabels" . | nindent 4 }}
