apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authsvc.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authsvc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authsvc.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authsvc.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/go/bin/webauthsvc"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
            - name: SLACK_OAUTH_CLIENT_ID
              value: {{ .Values.env.SLACK_OAUTH_CLIENT_ID | quote }}
            - name: SLACK_OAUTH_CLIENT_SECRET
              value: {{ .Values.env.SLACK_OAUTH_CLIENT_CLIENT | quote }}
            - name: WEB_HOST
              value: {{ .Values.global.webHost }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
