apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "authsvc.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authsvc.labels" . | nindent 4 }}
spec:
  hosts:
  - '*'
  gateways:
  - {{ .Values.global.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: {{ include "authsvc.fullname" . }}-web
        port:
          number: {{ .Values.service.http.port }}
