# Default values for stella.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

authsvc:
  enabled: true
  env:
    DATABASE_URL: postgres://PG_HOST:5432/stella
    SLACK_OAUTH_CLIENT_ID: ''
    SLACK_OAUTH_CLIENT_SECRET: ''

booksvc:
  enabled: true

frontend:
  enabled: true

global:
  webHost: http://localhost
  hosts: []
  gateway:
    name: stella
    tls:
      enabled: false
      secretName: stella-certs
