# Default values for stella.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

authsvc:
  enabled: true

booksvc:
  enabled: true

frontend:
  enabled: true

global:
  hosts: []
  # - library.buzzvil.com
  gateway:
    name: stella
    tls:
      enabled: false
      secretName: stella-certs
