# Default values for stella.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

authsvc:
  enabled: false

booksvc:
  enabled: false

frontend:
  enabled: true

global:
  gateway:
    name: stella
