apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratingsvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ratingsvc.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "ratingsvc.matchLabels" . | nindent 4 }}
