replicaCount: 1

image:
  repository: gcr.io/devops-229509/stella/authsvc
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  http:
    port: 8080
  grpc:
    port: 9000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
  # DATABASE_URL: postgres://stella:stella@stella-postgresql:5432/stella?sslmode=disable
  # SLACK_OAUTH_CLIENT_ID: ''
  # SLACK_OAUTH_CLIENT_SECRET: ''
