apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.global.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/xxx"
    route:
    - destination:
        host: {{ include "frontend.fullname" . }}
        port:
          number: {{ .Values.service.port }}
