apiVersion: v1
kind: Service
metadata:
  name: {{ include "rentalsvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rentalsvc.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "rentalsvc.matchLabels" . | nindent 4 }}
