apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "rentalsvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rentalsvc.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.global.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/stella.rental.v1.RentalService"
    route:
    - destination:
        host: {{ include "rentalsvc.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
      allowOrigin:
        - '*'
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - grpc-timeout
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
        - authorization
      maxAge: 86400s
      exposeHeaders:
        - grpc-status
        - grpc-message
      allowCredentials: true
