apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stella.gatewaysvc.fullname" . }}
  labels:
    {{- include "stella.gatewaysvc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gatewaysvc.replicaCount }}
  selector:
    matchLabels:
      {{- include "stella.gatewaysvc.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stella.gatewaysvc.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.gatewaysvc.image.repository }}:{{ .Values.gatewaysvc.image.tag }}"
          imagePullPolicy: {{ .Values.gatewaysvc.image.pullPolicy }}
          args:
            - --configfile=/config/traefik.toml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: web
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /config
              name: config
          resources:
            {{- toYaml .Values.gatewaysvc.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "stella.gatewaysvc.fullname" . }}
      {{- with .Values.gatewaysvc.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.gatewaysvc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.gatewaysvc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
