apiVersion: v1
kind: Service
metadata:
  name: {{ include "usersvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usersvc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "usersvc.matchLabels" . | nindent 4 }}
