apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "usersvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usersvc.labels" . | nindent 4 }}
spec:
  hosts:
  - '*'
  gateways:
  - {{ .Values.global.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /envoy.service.user
    route:
    - destination:
        host: {{ include "usersvc.fullname" . }}
        port:
          number: {{ .Values.service.port }}
