// Code generated by protoc-gen-go. DO NOT EDIT.
// source: booksvc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BooksQueryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooksQueryRequest) Reset()         { *m = BooksQueryRequest{} }
func (m *BooksQueryRequest) String() string { return proto.CompactTextString(m) }
func (*BooksQueryRequest) ProtoMessage()    {}
func (*BooksQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{1}
}

func (m *BooksQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooksQueryRequest.Unmarshal(m, b)
}
func (m *BooksQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooksQueryRequest.Marshal(b, m, deterministic)
}
func (m *BooksQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooksQueryRequest.Merge(m, src)
}
func (m *BooksQueryRequest) XXX_Size() int {
	return xxx_messageInfo_BooksQueryRequest.Size(m)
}
func (m *BooksQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BooksQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BooksQueryRequest proto.InternalMessageInfo

func (m *BooksQueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BooksQueryRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type BooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=Books,proto3" json:"Books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooksResponse) Reset()         { *m = BooksResponse{} }
func (m *BooksResponse) String() string { return proto.CompactTextString(m) }
func (*BooksResponse) ProtoMessage()    {}
func (*BooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{2}
}

func (m *BooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooksResponse.Unmarshal(m, b)
}
func (m *BooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooksResponse.Marshal(b, m, deterministic)
}
func (m *BooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooksResponse.Merge(m, src)
}
func (m *BooksResponse) XXX_Size() int {
	return xxx_messageInfo_BooksResponse.Size(m)
}
func (m *BooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BooksResponse proto.InternalMessageInfo

func (m *BooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "proto.Book")
	proto.RegisterType((*BooksQueryRequest)(nil), "proto.BooksQueryRequest")
	proto.RegisterType((*BooksResponse)(nil), "proto.BooksResponse")
}

func init() { proto.RegisterFile("booksvc.proto", fileDescriptor_4d08b9a0cac5ef76) }

var fileDescriptor_4d08b9a0cac5ef76 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x4e, 0xdd, 0x4a, 0x86, 0x40,
	0x10, 0x6d, 0xed, 0x53, 0x68, 0x16, 0x83, 0x86, 0x88, 0xa5, 0x2b, 0xdb, 0x2b, 0xe9, 0xc2, 0x0b,
	0x7b, 0x00, 0xa1, 0x07, 0x08, 0x5a, 0x9f, 0xc0, 0x9f, 0x01, 0x45, 0x72, 0x6c, 0x57, 0x85, 0xde,
	0x3e, 0x5c, 0xad, 0xec, 0x6a, 0xce, 0x9c, 0x9f, 0x99, 0x03, 0x71, 0xcd, 0x3c, 0xb8, 0xb5, 0xc9,
	0x26, 0xcb, 0x33, 0x63, 0xe8, 0x87, 0x7e, 0x86, 0xcb, 0x2b, 0xf3, 0x80, 0xb7, 0x10, 0xf4, 0xad,
	0x12, 0x89, 0x48, 0x43, 0x13, 0xf4, 0x2d, 0x22, 0x5c, 0xc6, 0xea, 0x83, 0x54, 0x90, 0x88, 0xf4,
	0xc6, 0x78, 0xac, 0x0b, 0xb8, 0xdb, 0xbc, 0xee, 0x7d, 0x21, 0xfb, 0x65, 0xe8, 0x73, 0x21, 0x37,
	0xff, 0x1a, 0xc5, 0x9f, 0x11, 0x1f, 0x20, 0xaa, 0x96, 0xb9, 0x63, 0x7b, 0xc4, 0x8f, 0x4d, 0xe7,
	0x10, 0xfb, 0x03, 0x86, 0xdc, 0xc4, 0xa3, 0x23, 0x7c, 0x82, 0xd0, 0x13, 0x4a, 0x24, 0xd7, 0xa9,
	0xcc, 0xe5, 0xde, 0x2d, 0xdb, 0x38, 0xb3, 0x2b, 0xf9, 0x1b, 0xc8, 0x0d, 0x94, 0x64, 0xd7, 0xbe,
	0x21, 0x2c, 0x40, 0x96, 0x54, 0xd9, 0xa6, 0xf3, 0x2a, 0xaa, 0x53, 0xe2, 0x5f, 0xaf, 0xc7, 0xfb,
	0xb3, 0xf2, 0xf3, 0x50, 0x5f, 0xd5, 0x91, 0xa7, 0x5f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf1,
	0x68, 0x2f, 0x83, 0x0f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	// rpc AddBook(AddBookRequest) returns (AddBookResponse) {}
	SearchBooks(ctx context.Context, in *BooksQueryRequest, opts ...grpc.CallOption) (*BooksResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) SearchBooks(ctx context.Context, in *BooksQueryRequest, opts ...grpc.CallOption) (*BooksResponse, error) {
	out := new(BooksResponse)
	err := c.cc.Invoke(ctx, "/proto.BookService/SearchBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	// rpc AddBook(AddBookRequest) returns (AddBookResponse) {}
	SearchBooks(context.Context, *BooksQueryRequest) (*BooksResponse, error)
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_SearchBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).SearchBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookService/SearchBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).SearchBooks(ctx, req.(*BooksQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchBooks",
			Handler:    _BookService_SearchBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booksvc.proto",
}
