// Code generated by protoc-gen-go. DO NOT EDIT.
// source: booksvc.proto

package stella_book_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Isbn                 string   `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Authors              []string `protobuf:"bytes,4,rep,name=authors,proto3" json:"authors,omitempty"`
	Publisher            string   `protobuf:"bytes,5,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CoverImage           string   `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetAuthors() []string {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *Book) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *Book) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Book) GetCoverImage() string {
	if m != nil {
		return m.CoverImage
	}
	return ""
}

type ListBooksRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Ids                  []int64  `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{1}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

func (m *ListBooksRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListBooksRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{2}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type GetBookRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Isbn                 string   `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{3}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetBookRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type CreateBookRequest struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Isbn                 string   `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Authors              []string `protobuf:"bytes,4,rep,name=authors,proto3" json:"authors,omitempty"`
	Publisher            string   `protobuf:"bytes,5,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CoverImage           string   `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d08b9a0cac5ef76, []int{4}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBookRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *CreateBookRequest) GetAuthors() []string {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *CreateBookRequest) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *CreateBookRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateBookRequest) GetCoverImage() string {
	if m != nil {
		return m.CoverImage
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "stella.book.v1.Book")
	proto.RegisterType((*ListBooksRequest)(nil), "stella.book.v1.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "stella.book.v1.ListBooksResponse")
	proto.RegisterType((*GetBookRequest)(nil), "stella.book.v1.GetBookRequest")
	proto.RegisterType((*CreateBookRequest)(nil), "stella.book.v1.CreateBookRequest")
}

func init() { proto.RegisterFile("booksvc.proto", fileDescriptor_4d08b9a0cac5ef76) }

var fileDescriptor_4d08b9a0cac5ef76 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x9b, 0xa4, 0x2f, 0x64, 0xca, 0xbf, 0xb4, 0xc3, 0x1f, 0x59, 0x8a, 0x68, 0xcc, 0x29,
	0x78, 0x08, 0x58, 0x3d, 0x0a, 0xa2, 0x1e, 0x8a, 0xe0, 0x69, 0xfd, 0x00, 0x92, 0xa4, 0xa3, 0x5d,
	0x9a, 0x66, 0x6b, 0x76, 0x9b, 0x8f, 0x25, 0xf8, 0xc1, 0xfc, 0x0e, 0xb2, 0xdb, 0xd6, 0xbe, 0xea,
	0xd9, 0xdb, 0xcc, 0xb3, 0xcf, 0x93, 0x9d, 0xfc, 0x86, 0x85, 0x7f, 0xa9, 0x94, 0x13, 0x55, 0x65,
	0xf1, 0xac, 0x94, 0x5a, 0x62, 0x47, 0x69, 0xca, 0xf3, 0x24, 0x36, 0x6a, 0x5c, 0x5d, 0x84, 0x1f,
	0x0e, 0xd4, 0xef, 0xa4, 0x9c, 0x60, 0x07, 0x5c, 0x31, 0x62, 0x4e, 0xe0, 0x44, 0x1e, 0x77, 0xc5,
	0x08, 0x11, 0xea, 0x45, 0x32, 0x25, 0xe6, 0x06, 0x4e, 0xe4, 0x73, 0x5b, 0x1b, 0x4d, 0xa8, 0xb4,
	0x60, 0xde, 0x42, 0x33, 0x35, 0x32, 0x68, 0x25, 0x73, 0x3d, 0x96, 0xa5, 0x62, 0xf5, 0xc0, 0x8b,
	0x7c, 0xbe, 0x6a, 0xf1, 0x18, 0xfc, 0xd9, 0x3c, 0xcd, 0x85, 0x1a, 0x53, 0xc9, 0x1a, 0x36, 0xb2,
	0x16, 0x4c, 0x2e, 0x93, 0x85, 0xa6, 0x42, 0xb3, 0xa6, 0x3d, 0x5b, 0xb5, 0x78, 0x0a, 0xed, 0x4c,
	0x56, 0x54, 0x3e, 0x8b, 0x69, 0xf2, 0x4a, 0xac, 0x65, 0x4f, 0xc1, 0x4a, 0x0f, 0x46, 0x09, 0xaf,
	0xa1, 0xfb, 0x28, 0x94, 0x36, 0x63, 0x2b, 0x4e, 0x6f, 0x73, 0x52, 0x1a, 0x8f, 0xa0, 0xf9, 0x22,
	0x72, 0x4d, 0xa5, 0xfd, 0x05, 0x9f, 0x2f, 0x3b, 0xec, 0x82, 0x27, 0x46, 0x8a, 0xb9, 0x81, 0x17,
	0x79, 0xdc, 0x94, 0xe1, 0x0d, 0xf4, 0x36, 0xd2, 0x6a, 0x26, 0x0b, 0x45, 0x78, 0x0e, 0x0d, 0xcb,
	0x89, 0x39, 0x81, 0x17, 0xb5, 0x07, 0xff, 0xe3, 0x6d, 0x4c, 0xb1, 0x71, 0xf3, 0x85, 0x25, 0xbc,
	0x82, 0xce, 0x90, 0x6c, 0x7e, 0x75, 0xf9, 0x01, 0x76, 0x96, 0x93, 0xbb, 0xe6, 0x14, 0xbe, 0x3b,
	0xd0, 0xbb, 0x2f, 0x29, 0xd1, 0xb4, 0x99, 0xfc, 0xbb, 0x94, 0x07, 0x9f, 0x0e, 0xb4, 0xcd, 0xa8,
	0x4f, 0x54, 0x56, 0x22, 0x23, 0xe4, 0xe0, 0x7f, 0x73, 0xc3, 0x60, 0x17, 0xd0, 0xee, 0x42, 0xfa,
	0x67, 0xbf, 0x38, 0x16, 0xd0, 0xc3, 0x1a, 0xde, 0x42, 0x6b, 0x89, 0x12, 0x4f, 0x76, 0xfd, 0xdb,
	0x8c, 0xfb, 0x07, 0x57, 0x12, 0xd6, 0x70, 0x08, 0xb0, 0xc6, 0x8a, 0x7b, 0xb7, 0xee, 0x21, 0xff,
	0xe9, 0x43, 0x69, 0xd3, 0x3e, 0x90, 0xcb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xf3, 0xdc,
	0x78, 0x31, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/stella.book.v1.BookService/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/stella.book.v1.BookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/stella.book.v1.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	CreateBook(context.Context, *CreateBookRequest) (*Book, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) ListBooks(ctx context.Context, req *ListBooksRequest) (*ListBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (*UnimplementedBookServiceServer) GetBook(ctx context.Context, req *GetBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookServiceServer) CreateBook(ctx context.Context, req *CreateBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.book.v1.BookService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.book.v1.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stella.book.v1.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stella.book.v1.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _BookService_ListBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booksvc.proto",
}
