apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: liam.hwang@buzzvil.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:
      - name: route53
        route53:
          accessKeyID: AKIAYTR3WEPSKGWQRNNI
          region: ap-northeast-1
          secretAccessKeySecretRef:
            name: aws-route53-credential
            key: secret-access-key
